name: "Tests"

on:
  push:
    branches: [main]
  pull_request:

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
        dependencies:
          - "highest"
          - "lowest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          tools: "flex"

      - name: "Get composer cache directory ≡ƒÅÄ∩╕Å"
        id: "composer-cache"
        run: |
          echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: "Cache dependencies"
        uses: "actions/cache@v3"
        with:
          path: "${{ steps.composer-cache.outputs.dir }}"
          key: '${{ runner.os }}-composer-${{ hashFiles("/composer.lock") }}-php-${{ matrix.php-version }}-deps-${{ matrix.dependencies }}'
          restore-keys: "${{ runner.os }}-composer-"

      - name: "Install dependencies"
        run: |
          composer install --prefer-dist --no-progress

      - name: "Run PHPUnit"
        run: "bin/phpunit --coverage-text --testdox --configuration phpunit.dist.xml"
